In [23]:
import numpy as np
from numpy import array
import tensorflow as tf
from keras.layers  import Dense,InputLayer
from keras.initializers import constant

Importing Libraries

In [24]:
X=array([[0.5,0.6,0.1]])

Setting up arrays

In [25]:
w1=array([[0.2,0.3,0.2],[0.1,0.1,0.1]])


Adding weights


In [26]:
X.shape

(1, 3)

Showing shape and size of the arrray

In [41]:
layer1=InputLayer(3)
layer2=Dense(10,activation='tanh')
layer3=Dense(1,activation='sigmoid')

Inputing layers and number of neurons

In [42]:
layer2(layer1(X))

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-0.09103143, -0.45956597,  0.11235788, -0.0784435 ,  0.08747004,
         0.62581015, -0.0689294 ,  0.44991452,  0.13740999, -0.09422014]],
      dtype=float32)>

In [43]:
layer2.weights

[<tf.Variable 'dense_14/kernel:0' shape=(3, 10) dtype=float32, numpy=
 array([[-0.08559263, -0.38328025,  0.59995127,  0.1827578 , -0.59622896,
          0.6770179 , -0.07067454,  0.46040082,  0.6115761 ,  0.27351302],
        [-0.07421237, -0.6125612 , -0.267763  , -0.28494352,  0.6384468 ,
          0.55646086, -0.15133995,  0.37785542, -0.2498487 , -0.47877383],
        [-0.03960401,  0.6241603 , -0.26483515,  0.00982225,  0.02740526,
          0.6211369 ,  0.5710236 ,  0.27679443, -0.17594033,  0.5600735 ]],
       dtype=float32)>,
 <tf.Variable 'dense_14/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

Viewing weights of layer2

In [44]:
layer3(layer2(layer1(X)))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.6429495]], dtype=float32)>

In [45]:
layer3.weights

[<tf.Variable 'dense_15/kernel:0' shape=(10, 1) dtype=float32, numpy=
 array([[-0.27897465],
        [-0.46798086],
        [ 0.45945066],
        [-0.08420467],
        [ 0.03898776],
        [ 0.50600594],
        [ 0.72103614],
        [-0.19488126],
        [ 0.5654767 ],
        [-0.30887035]], dtype=float32)>,
 <tf.Variable 'dense_15/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

Viewing layer 3 weights