In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [ ]:
data=pd.read_csv('/content/modified_data.csv') #grab the dataset

In [ ]:
data.head() #view the dataset

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 77 columns]

#Step Two:  Prepare Dataset
#Search For Missing Value


In [ ]:
data.drop('Id', axis=1,inplace=True)

In [ ]:
data.head()

MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0          60       RL         65.0  ...        WD        Normal    208500
1          20       RL         80.0  ...        WD        Normal    181500
2          60       RL         68.0  ...        WD        Normal    223500
3          70       RL         60.0  ...        WD       Abnorml    140000
4          60       RL         84.0  ...        WD        Normal    250000

[5 rows x 76 columns]

In [ ]:
data.shape #check the dataset 1460-rows 76 -columns


(1460, 76)

In [ ]:
data.isna().any()

MSSubClass       False
MSZoning         False
LotFrontage       True
LotArea          False
Street           False
                 ...  
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool

In [ ]:
original_features=list(data.columns)
original_features

['MSSubClass',
 'MSZoning',
 'LotFrontage',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch

In [ ]:
features_with_missing=list(data.columns[data.isna().any()])
features_with_missing
len(features_with_missing)

15

In [ ]:
original_features=list(data.columns)
original_features
len(original_features)

76

In [ ]:
for feature in features_with_missing:
  print(feature,' ',(data[feature].isna().sum())/len(data)*100)

LotFrontage   17.73972602739726
MasVnrType   0.547945205479452
MasVnrArea   0.547945205479452
BsmtQual   2.5342465753424657
BsmtCond   2.5342465753424657
BsmtExposure   2.6027397260273974
BsmtFinType1   2.5342465753424657
BsmtFinType2   2.6027397260273974
Electrical   0.0684931506849315
FireplaceQu   47.26027397260274
GarageType   5.5479452054794525
GarageYrBlt   5.5479452054794525
GarageFinish   5.5479452054794525
GarageQual   5.5479452054794525
GarageCond   5.5479452054794525


In [ ]:
data.dropna(axis=1,thresh=0.5*(len(data)),inplace=True) #drop feature with missing values

In [ ]:
mean_fill=['LotFrontage', 'MasVnrArea'] #fill using mean
bfill=['FireplaceQu'] #backward fill
ffill=list(set(features_with_missing)-set(mean_fill)-set(bfill)) #forward fill

In [ ]:
ffill

['GarageYrBlt',
 'BsmtQual',
 'BsmtCond',
 'MasVnrType',
 'BsmtFinType2',
 'BsmtExposure',
 'Electrical',
 'GarageQual',
 'GarageFinish',
 'GarageCond',
 'BsmtFinType1',
 'GarageType']

In [ ]:
for feature in mean_fill:
  data[feature].fillna(data[feature].mean(),inplace=True)

In [ ]:
for feature in ffill:
  data[feature].fillna(method='ffill',inplace=True)

In [ ]:
for feature in bfill:
  data[feature].fillna(method='bfill',inplace=True)

In [ ]:
data.isna().any()

MSSubClass       False
MSZoning         False
LotFrontage      False
LotArea          False
Street           False
                 ...  
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool


#Encode the Dataset



In [ ]:
cat_data=data.select_dtypes(include=['object'])
cat_data.head(2) #viewing the categorical features which are features without numbers

MSZoning Street LotShape  ... PavedDrive SaleType SaleCondition
0       RL   Pave      Reg  ...          Y       WD        Normal
1       RL   Pave      Reg  ...          Y       WD        Normal

[2 rows x 39 columns]

In [ ]:
cat_features=list(cat_data.columns)
cat_features #features that need encoding

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [ ]:
nominal=['MSZoning', 'LandContour','LotConfig','Neighborhood']
ordinal=list(set(cat_features)-set(nominal))
numerical=list(set(original_features)-set(cat_features))
target=['SalePrice']

In [ ]:
data[nominal]

MSZoning LandContour LotConfig Neighborhood
0          RL         Lvl    Inside      CollgCr
1          RL         Lvl       FR2      Veenker
2          RL         Lvl    Inside      CollgCr
3          RL         Lvl    Corner      Crawfor
4          RL         Lvl       FR2      NoRidge
...       ...         ...       ...          ...
1455       RL         Lvl    Inside      Gilbert
1456       RL         Lvl    Inside       NWAmes
1457       RL         Lvl    Inside      Crawfor
1458       RL         Lvl    Inside        NAmes
1459       RL         Lvl    Inside      Edwards

[1460 rows x 4 columns]

In [ ]:
data[numerical]

BedroomAbvGr  2ndFlrSF  TotalBsmtSF  ...  ScreenPorch  GarageCars  YrSold
0                3       854          856  ...            0           2    2008
1                3         0         1262  ...            0           2    2007
2                3       866          920  ...            0           2    2008
3                3       756          756  ...            0           3    2006
4                4      1053         1145  ...            0           3    2008
...            ...       ...          ...  ...          ...         ...     ...
1455             3       694          953  ...            0           2    2007
1456             3         0         1542  ...            0           2    2010
1457             4      1152         1152  ...            0           1    2010
1458             2         0         1078  ...            0           1    2010
1459             3         0         1256  ...            0           1    2008

[1460 rows x 37 columns]

In [ ]:
for feature in ordinal: 
  data[feature]=(data[feature].astype('category')).cat.codes

In [ ]:
df_nominal=pd.get_dummies(data[nominal]) #one hot encoding

In [ ]:
df_ordinal=data[ordinal]


In [ ]:
df_numerical=data[numerical]

In [ ]:
encoded_data=pd.concat([df_numerical, df_nominal, df_ordinal], axis=1)

In [ ]:
encoded_data.head(3)

BedroomAbvGr  2ndFlrSF  TotalBsmtSF  ...  PavedDrive  Electrical  FireplaceQu
0             3       854          856  ...           2           4            5
1             3         0         1262  ...           2           4            5
2             3       866          920  ...           2           4            5

[3 rows x 76 columns]

#Data Normalization

In [ ]:
X=encoded_data.drop('SalePrice', axis=1)

In [ ]:
y=data[target]
y

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [ ]:
X.to_numpy()
X

BedroomAbvGr  2ndFlrSF  TotalBsmtSF  ...  PavedDrive  Electrical  FireplaceQu
0                3       854          856  ...           2           4            5
1                3         0         1262  ...           2           4            5
2                3       866          920  ...           2           4            5
3                3       756          756  ...           2           4            3
4                4      1053         1145  ...           2           4            5
...            ...       ...          ...  ...         ...         ...          ...
1455             3       694          953  ...           2           4            5
1456             3         0         1542  ...           2           4            5
1457             4      1152         1152  ...           2           4            3
1458             2         0         1078  ...           2           0            0
1459             3         0         1256  ...           2           4            0

[1460 rows x 75 columns]

In [ ]:
y=y.to_numpy() #change to a matrix
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [ ]:
X.shape #rows and columns

(1460, 75)

In [ ]:
y.shape

(1460, 1)

In [ ]:
X=StandardScaler().fit_transform(X)
y=StandardScaler().fit_transform(y)

In [ ]:
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

In [ ]:
X.shape

(1460, 75)

#PCA Dimensionality Reduction


In [ ]:
pca=PCA(n_components=2)
p_components=pca.fit_transform(X)

In [ ]:
p_components

array([[ 2.15078401,  0.05459886],
       [ 0.14094996, -1.72696945],
       [ 2.57197685, -0.07926865],
       ...,
       [ 1.33094974,  2.7218465 ],
       [-2.93359946, -2.47638569],
       [-0.78227828, -2.36910706]])

------------------------------------------------------

In [ ]:
pca.explained_variance_ratio_n 

array([0.13688131, 0.05387667])

You could do this or 👆🏾 this 👇🏾

In [ ]:
pca_var=PCA(0.9) #90%
new_pcs=pca_var.fit_transform(X)

In [ ]:
pca_var.n_components_

49

-------------------------------------------