<a href="https://colab.research.google.com/github/kioko91/ML-labs/blob/main/ML_Class_Lab3ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from numpy.linalg import det,inv
from numpy import array,matrix

In [18]:
mat_a=matrix([[-2,3,-1],[1,2,-1],[-2,-1,1]])

In [19]:
mat_a

matrix([[-2,  3, -1],
        [ 1,  2, -1],
        [-2, -1,  1]])

In [20]:
det(mat_a) #computed differently/efficiently

-1.9999999999999998

In [21]:
inv(mat_a)

matrix([[-0.5,  1. ,  0.5],
        [-0.5,  2. ,  1.5],
        [-1.5,  4. ,  3.5]])

In [23]:
cof_matrix=array([[-2,3,-1],[1,2,-1],[-2,-1,1]])
Y=array([[1],[4],[-3]])

In [24]:
Y.shape

(3, 1)

In [32]:
Y.reshape(3,1)

array([[ 1],
       [ 4],
       [-3]])

In [33]:
Y.T

array([[ 1,  4, -3]])

In [30]:
inv(cof_matrix)@Y.T

ValueError: ignored