<a href="https://colab.research.google.com/github/kioko91/ML-labs/blob/main/ML_class_lab1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import random
import pandas as pd


In [ ]:
random.binomial(100,0.5,10)

array([51, 51, 52, 56, 47, 56, 55, 46, 41, 44])

In [ ]:
random.poisson(2,15)

array([0, 3, 1, 1, 3, 2, 0, 1, 3, 1, 1, 4, 0, 0, 1])

In [ ]:
random.uniform(10,100,20)

array([39.55644987, 96.17903505, 17.70390292, 59.87435833, 67.92837602,
       39.41765981, 10.63552423, 44.87738031, 66.37325956, 61.08627099,
       75.74684521, 33.66743488, 70.22089958, 77.89175454, 61.23075331,
       43.64344477, 72.98259843, 33.97301032, 28.49733726, 81.10960121])

In [ ]:
dummy_data={'Age':random.normal(33,1,15), 'Gender':random.binomial(1,0.5,15), 'Location':random.poisson(2,15), 'Income':random.uniform(30,100,15)}

In [ ]:
dummy_data

In [ ]:
pd.DataFrame(dummy_data)

Age  Gender  Location     Income
0   33.013750       1         2  47.225180
1   32.651878       1         3  58.957212
2   30.653838       0         3  59.581788
3   32.806597       1         4  83.663369
4   33.897508       1         1  37.007261
5   32.738577       1         5  92.648646
6   34.780950       1         1  92.622329
7   34.376167       1         1  71.869219
8   32.142532       0         1  75.551085
9   33.090834       1         3  35.182805
10  32.567221       0         2  85.085701
11  32.140787       1         2  60.853281
12  32.025646       1         2  37.330492
13  32.659079       0         3  38.527412
14  32.253984       0         2  64.025443